x-common-keys: &common-keys
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
  networks:
    - application-network
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 200M
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    TZ: ${TZ}
    PUID: ${PUID}
    PGID: ${PGID}

services:
  example-webapp:
    depends_on:
      - traefik
    image: my/app:version
    <<: *common-keys
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${EXAMPLE_APPLICATION_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=${EXAMPLE_APPLICATION_LISTENING_PORT}"

  traefik:
    image: traefik:v3.0
    <<: *common-keys
    ports:
      - 80:80
      - 443:443
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN} 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./appdata/traefik/traefik.yaml:/etc/traefik/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_BASE64_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${TOP_LEVEL_DOMAIN}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${TOP_LEVEL_DOMAIN}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
   application-network:
